name: Build and Deploy Sphinx Docs

on:
  push:
    branches:
      - docs/trying-sphinx  # or change to your default branch

jobs:
  build-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: 3.11  # or your preferred Python version

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install sphinx
        pip install -r docs/requirements.txt || true  # optional, if you use it

    - name: Generate API docs
      run: |
        sphinx-apidoc -o docs src/zenith --force
      # NOTE: Add --no-toc if you have your own personal index.rst with .. toctree::

    - name: Build HTML docs
      run: |
        cd docs
        make html SPHINXOPTS=-W

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v4
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: docs/_build/html
        publish_branch: gh-pages
        force_orphan: true